#ifndef ErrorManager_H
#define ErrorManager_H 1


#include <iostream>
#include <vector>
#include <string>
#include "magic_enum.hpp"

/**
 * A class to handle software error
 *
 * @author Tsubasa Tamba,
 * @date 2023-04-27
 */

namespace balloon {

enum class ErrorType {
  RECEIVE_COMMAND_Ras2_COMMUNICATION_ERROR = 0,
  RECEIVE_COMMAND_SELECT_ERROR = 1,
  RECEIVE_COMMAND_SREAD_ERROR = 2,
  INVALID_COMMAND = 3,
  PIGPIO_START_ERROR = 4,
  SPI_OPEN_ERROR = 5,
  RTD_DATA_AQUISITION_ERROR_1 = 6,
  RTD_DATA_AQUISITION_ERROR_2 = 7,
  RTD_DATA_AQUISITION_ERROR_3 = 8,
  RTD_DATA_AQUISITION_ERROR_4 = 9,
  RTD_DATA_AQUISITION_ERROR_5 = 10,
  ENV_DATA_AQUISITION_ERROR_1 = 11,
  ENV_DATA_AQUISITION_ERROR_2 = 12,
  ENV_DATA_AQUISITION_ERROR_3 = 13,
  ENV_DATA_AQUISITION_ERROR_4 = 14,
  ENV_DATA_AQUISITION_ERROR_5 = 15,
  ACCEL_DEVICE_NOT_FOUND = 16,
  ACCEL_DATA_AQUISITION_ERROR = 17,
  SLOW_ADC_DATA_AQUISITION_ERROR = 18,
  GET_SD_CAPACITY_ERROR = 19,
  ANALOG_DISCOVERY_INITIALIZE_ERROR = 20,
  ANALOG_DISCOVERY_NOT_CONNECTED = 21,
  ONLY_ONE_ANALOG_DISCOVERY_CONNECTED = 22,
  TPC_HV_INVALID_CHANNEL = 23,
  TPC_HV_INVALID_VOLTAGE = 24,
  PMT_HV_INVALID_CHANNEL = 25,
  RECEIVE_EU_RESPONSE_INIT_ERROR = 26,
  SEND_TELEMETRY_UNKNOWN_COMM_TYPE_ERROR = 27,
  SEND_TELEMETRY_Ras2_COMMUNICATION_ERROR = 28,
  SEND_TELEMETRY_COMMUNICATION_ERROR = 29,
  SEND_TELEMETRY_SWRITE_ERROR = 30,
  SHUTDOWN_REJECTED = 31,
  REBOOT_REJECTED = 32,
  SOFTWARE_STOP_REJECTED = 33,
//ERROR about EU Raspi
  MOTOR_FAULT_DETECTED=34,
  MOTOR_ENCODER_ERROR=35,
  MOTOR_COMUTATION_FAULT=36,
  MOTOR_ILLEGAL_HALL=37,
  MOTOR_OVER_CURRENT=38,
  EC_UNKNOWN_COMMAND=39,
  EC_INDEX_OUTOFRANGE=40,
  EC_PROGRAM_NOT_RUNNING=41,
  EC_RESERVE=42,
  MODULE_ACCESS_ERROR = 62,
  OTHER_ERRORS = 63
};

class ErrorManager
{
public:
  ErrorManager();
  void resetError();
  void setError(ErrorType v);
  void clearError(ErrorType v);
  static int strToBit(const std::string& s);
  static std::string bitToStr(int v);
  
  uint64_t ErrorCode() { return errorCode_; }

private:
  uint64_t errorCode_ = 0;
  uint16_t errorNum_ = 0;
};

} /* namespace balloon */

#endif /* ErrorManager_H */
